### ISSUE TITLE
[core.Decorators] Better help messages

### ISSUE THREAD

**Issue by ns-phennessy** [ns-phennessy/Arcbot#29]
Had an idea to make command help messages easier

Add an option to the `command` decorator to give the command a name. That way it doesn't rely on the method name for that.

**Comment by ZetaHunter** [comment]
I've added my version of help command to my fork.
It prints by plugins showing status of plugin (if plugin is enabled it will also print it's commands)
Discord Example: http://i.imgur.com/dmsHTRc.png

**Comment by ns-phennessy** [comment]
fixed with: 2c5e600290d8af10b1648af5b65a348042335284
