### ISSUE TITLE
Needs to be updated???

### ISSUE THREAD

**Issue by TheFlamingToast** [ns-phennessy/Arcbot#53]
Needs to be updated?. `$ python3.5 bot.py
Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    from core.Core import Bot
  File "/home/CENSORED/Arcbot/core/Core.py", line 21, in <module>
    import conf.settings as config
ImportError: No module named 'conf'`
Your git probably has to be updated so the clone is accurate. But I am just an amateur, so any help?

**Comment by ns-phennessy** [comment]
Applogies; I was working on making some breaking changes but went on vacation half way though lmao.

**Comment by TheFlamingToast** [comment]
Okay. Thanks!

**Comment by ns-phennessy** [comment]
You could back out to this git ref: https://github.com/ns-phennessy/Arcbot/commit/fe357b4d4371774630138df13b098255505c2607

I've been doing a lot of refactoring lately so master may not be totally stable

**Comment by TheFlamingToast** [comment]
Okay.

**Comment by TheFlamingToast** [comment]
Is there anything else?

**Comment by TheFlamingToast** [comment]
The command is actually `pip install -r REQUIREMENTS.txt`, not `pip -r REQUIREMENTS.txt`.
